Refactored Node dependencies & removed Shrinkpack
cuemby/hapi-bootstrap pull request #3
Opened 2016-09-29 02:02 UTC by aramonc

* Cleaned up the `.gitignore` file.
* Removed the shrinkpacked dependency tarballs
* Removed shrinkpack from dev dependencies & scripts.

2016-09-29 02:26 UTC, ar4mirez requested changes

2016-09-29 02:26 UTC, ar4mirez commented on package.json
> +    "label": "^0.2.2",
@aramonc `label` isn't the test runner the package is `lab` sorry maybe was my mistake.

2016-09-30 04:24 UTC, aramonc commented on package.json
> +    "label": "^0.2.2",
@ar4mirez this is fixed. Latest commit also added `shrinkpack` back.

2016-10-01 12:37 UTC, aramonc commented on package.json
> +    "label": "^0.2.2",
done

2016-10-01 12:39 UTC, merged